// frontend/src/app/tenant/dashboard/components/mockData.ts

export const directorDashboardData = {
  kpiCards: [
    {
      icon: "users",
      label: "Total Karyawan",
      value: "2,500",
      change: "+2.5%",
      changeLabel: "dari bulan lalu",
      changeColor: "text-green-500",
    },
    {
      icon: "briefcase",
      label: "Total Proyek",
      value: "120",
      change: "+1.2%",
      changeLabel: "dari bulan lalu",
      changeColor: "text-green-500",
    },
    {
      icon: "clock",
      label: "Rata-rata Waktu Proses",
      value: "3 Hari",
      change: "-0.5 Hari",
      changeLabel: "dari bulan lalu",
      changeColor: "text-green-500",
    },
    {
      icon: "clipboard",
      label: "Kepatuhan",
      value: "95%",
      change: "+1.0%",
      changeLabel: "dari bulan lalu",
      changeColor: "text-green-500",
    },
    {
      icon: "dollar",
      label: "Total Pendapatan",
      value: "Rp 150M",
      change: "+5.0%",
      changeLabel: "dari bulan lalu",
      changeColor: "text-green-500",
    },
  ],
  sptStatus: {
    title: "Status SPT",
    subtitle: "Ringkasan status SPT bulanan",
    description: "Data diambil dari 12 bulan terakhir",
    chartData: [
      { month: "Jan", dihasilkan: 150, pending: 30, disetujui: 120 },
      { month: "Feb", dihasilkan: 160, pending: 25, disetujui: 135 },
      { month: "Mar", dihasilkan: 170, pending: 35, disetujui: 135 },
      { month: "Apr", dihasilkan: 180, pending: 20, disetujui: 160 },
      { month: "Mei", dihasilkan: 190, pending: 40, disetujui: 150 },
      { month: "Jun", dihasilkan: 200, pending: 30, disetujui: 170 },
      { month: "Jul", dihasilkan: 210, pending: 25, disetujui: 185 },
      { month: "Agu", dihasilkan: 220, pending: 30, disetujui: 190 },
      { month: "Sep", dihasilkan: 230, pending: 20, disetujui: 210 },
      { month: "Okt", dihasilkan: 240, pending: 35, disetujui: 205 },
      { month: "Nov", dihasilkan: 250, pending: 25, disetujui: 225 },
      { month: "Des", dihasilkan: 260, pending: 30, disetujui: 230 },
    ],
  },
  trendData: {
    title: "Tren Kepatuhan Pajak",
    subtitle: "Persentase kepatuhan pajak bulanan",
    description: "Tren menunjukkan peningkatan kepatuhan secara stabil",
    chartData: [
      { month: "Jan", percentage: 88.5 },
      { month: "Feb", percentage: 89.2 },
      { month: "Mar", percentage: 90.1 },
      { month: "Apr", percentage: 90.5 },
      { month: "Mei", percentage: 91.0 },
      { month: "Jun", percentage: 91.7 },
      { month: "Jul", percentage: 92.0 },
      { month: "Agu", percentage: 92.5 },
      { month: "Sep", percentage: 92.8 },
      { month: "Okt", percentage: 93.1 },
      { month: "Nov", percentage: 93.5 },
      { month: "Des", percentage: 94.0 },
    ],
  },
  complianceOverview: {
    title: "Ringkasan Kepatuhan",
    subtitle: "Status kepatuhan berdasarkan kategori",
    items: [
      {
        label: "SPT Tahunan",
        count: 50,
        percentage: 95,
        color: "#16A34A",
        bgColor: "#DAFAE3",
      },
      {
        label: "SPT Masa PPh",
        count: 120,
        percentage: 92,
        color: "#F9BE6C",
        bgColor: "#FFF8ED",
      },
      {
        label: "SPT Masa PPN",
        count: 100,
        percentage: 98,
        color: "#4F46E5",
        bgColor: "#EEF2FF",
      },
      {
        label: "Lain-lain",
        count: 10,
        percentage: 80,
        color: "#E3646A",
        bgColor: "#FBECEB",
      },
    ],
    period: "Per Desember 2025",
    totalCount: 280,
  },
  projectRisk: {
    title: "Ringkasan Risiko Proyek",
    subtitle: "Proyek dengan risiko tinggi",
    items: [
      {
        label: "Proyek A (Kepatuhan PPh Pasal 21)",
        count: 5,
        action: "Review",
        actionVariant: "destructive",
      },
      {
        label: "Proyek B (Dokumentasi Transfer Pricing)",
        count: 3,
        action: "Review",
        actionVariant: "default",
      },
      {
        label: "Proyek C (SPT Masa PPN Kurang Bayar)",
        count: 4,
        action: "Review",
        actionVariant: "destructive",
      },
    ],
    footer: {
      label: "Total Proyek Berisiko",
      value: "12 Proyek",
    },
  },
  bastInvoice: {
    title: "Status BAST & Invoice",
    items: [
      {
        label: "BAST Belum Diterbitkan",
        count: 8,
        action: "Buat BAST",
      },
      {
        label: "Invoice Belum Terbayar",
        count: 15,
        action: "Kirim Pengingat",
      },
      {
        label: "Dokumen Kurang Lengkap",
        count: 5,
        action: "Lengkapi Dokumen",
      },
    ],
    footer: {
      label: "Total Tertunda",
      value: "28 Dokumen",
    },
    actions: [{ label: "Lihat Semua" }, { label: "Buat Baru" }],
  },
  topAttention: {
    title: "Top Perhatian",
    subtitle: "Daftar proyek yang membutuhkan perhatian segera",
    columns: [
      "Kode Proyek",
      "Klien",
      "Periode",
      "Modul",
      "Hari Terlambat",
      "Pemilik",
      "Level Risiko",
      "Tindakan",
    ],
    rows: [
      {
        projectCode: "PROJ-001",
        client: "PT Maju Terus",
        period: "Jan-Mar 2025",
        module: "PPh Badan",
        daysOverdue: "15 Hari",
        owner: "Budi",
        riskLevel: "Tinggi",
        riskVariant: "destructive",
      },
      {
        projectCode: "PROJ-002",
        client: "CV Sejahtera",
        period: "Apr-Jun 2025",
        module: "PPN",
        daysOverdue: "10 Hari",
        owner: "Ani",
        riskLevel: "Sedang",
        riskVariant: "default",
      },
      {
        projectCode: "PROJ-003",
        client: "PT Jaya Abadi",
        period: "Jul-Sep 2025",
        module: "PPh 21",
        daysOverdue: "20 Hari",
        owner: "Candra",
        riskLevel: "Tinggi",
        riskVariant: "destructive",
      },
      {
        projectCode: "PROJ-004",
        client: "UD Makmur",
        period: "Okt-Des 2025",
        module: "PPh 23",
        daysOverdue: "5 Hari",
        owner: "Dewi",
        riskLevel: "Rendah",
        riskVariant: "default",
      },
    ],
  },
};
